package visao;

import cliente.Cliente;
import java.io.IOException;
import javax.swing.JOptionPane;
import cliente.Mensagem;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author caio
 */
public class TelaConexao extends javax.swing.JFrame {

    /**
     * Creates new form TelaConexao
     */
    public TelaConexao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNomeTela = new javax.swing.JLabel();
        tfEndConexao = new javax.swing.JTextField();
        lblStatusConexao = new javax.swing.JLabel();
        btnConexao = new javax.swing.JButton();
        lblEndConexao = new javax.swing.JLabel();
        lblPortaConexao = new javax.swing.JLabel();
        tfPortaConexao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNomeTela.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        lblNomeTela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeTela.setText("Programa Cliente - Jogo da Forca");

        tfEndConexao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfEndConexao.setText("127.0.1.1");
        tfEndConexao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEndConexaoActionPerformed(evt);
            }
        });

        lblStatusConexao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatusConexao.setText("No connection");

        btnConexao.setText("Conectar");
        btnConexao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConexaoActionPerformed(evt);
            }
        });

        lblEndConexao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEndConexao.setText("Digite o endereço do servidor:");

        lblPortaConexao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPortaConexao.setText("Digite a porta:");

        tfPortaConexao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfPortaConexao.setText("12345");
        tfPortaConexao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPortaConexaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(tfPortaConexao))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(193, 193, 193)
                                .addComponent(tfEndConexao, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConexao)
                        .addGap(271, 271, 271))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeTela, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                            .addComponent(lblStatusConexao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEndConexao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPortaConexao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomeTela)
                .addGap(53, 53, 53)
                .addComponent(lblStatusConexao)
                .addGap(29, 29, 29)
                .addComponent(lblEndConexao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEndConexao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPortaConexao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPortaConexao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConexao)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConexaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConexaoActionPerformed
        try {
            Cliente cliente = new Cliente();
            int porta = Integer.parseInt(tfPortaConexao.getText());
            String host = tfEndConexao.getText();
            cliente.conectarCliente(host, porta);
            this.setVisible(false);
            TelaJogo tc = new TelaJogo(cliente);
            tc.setVisible(true);

            Mensagem m;
            m = tc.controle.receberMensagem();
            if (tc.controle.getId().equalsIgnoreCase("0")) {
                tc.setTitle("Primeiro Jogador");
                tc.primeiroJogador(m);

            } else {
                tc.setTitle("Segundo Jogador");
                tc.segundoJogador(m);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_btnConexaoActionPerformed

    private void tfEndConexaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEndConexaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEndConexaoActionPerformed

    private void tfPortaConexaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPortaConexaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPortaConexaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConexao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConexao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConexao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConexao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaConexao().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConexao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEndConexao;
    private javax.swing.JLabel lblNomeTela;
    private javax.swing.JLabel lblPortaConexao;
    private javax.swing.JLabel lblStatusConexao;
    private javax.swing.JTextField tfEndConexao;
    private javax.swing.JTextField tfPortaConexao;
    // End of variables declaration//GEN-END:variables
}
